spring:
  application:
    name: url-shortener
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/url_shortener}
    username: ${DATABASE_USERNAME:url_shortener}
    password: ${DATABASE_PASSWORD:url_shortener}

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
  endpoints:
    web:
      exposure:
        include: health

security:
  api-key: ${API_KEY:dev-key-not-a-secret}
logging:
  structured:
    format:
      console: ecs
